name: "TEST Integration"

on:
  workflow_dispatch:
  workflow_run:
    workflows: 
      - TEST Unit
    types: 
      - completed

run-name: TEST Integration ${{ github.deploy_target }} by @${{ github.actor }}

jobs: 
  run-integration-tests-cf-env-with-edge-capi:
    name: Integration tests with EDGE CAPI
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/integration-reusable.yml
    with:
      os: ubuntu-latest
      name: Integration EDGE CAPI
    secrets: inherit

  run-integration-tests-cf-env-with-edge-capi-with-client-creds:
    name: EDGE CAPI and client creds
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/integration-reusable.yml
    with:
      os: ubuntu-latest
      name: Integration EDGE CAPI client creds
    secrets: inherit
