name: "TEST asdf"

on:
  workflow_dispatch:
  workflow_run:
    workflows: 
      - TEST Unit
    types: 
      - completed

jobs: 
  test-asdf:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: test-asdf
    defaults:
      run:
        shell: bash
    steps:
    - uses: LouisBrunner/checks-action@v1.6.0
      if: always()
      id: check
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "test-asdf"
        status: in_progress
        repo: ${{github.event.workflow_run.head_repository.full_name}}
        sha:  ${{github.event.workflow_run.head_sha}}
        output: |
          {"summary":"I'm starting"}
    - name: Checkout cli
      uses: actions/checkout@v3
      with:
        ref: ${{github.event.workflow_run.head_sha}}
    - id: test-secret
      name: test secret
      env:
        test_secret: ${{ secrets.TEST_SECRET }}
        test_var: ${{ vars.TEST_VAR }}
      run: |
        if [ test_secret1 == $test_secret ]; then
          echo "I SEE SECERET"
        fi
        echo  $test_var
        cat testfile
    - uses: LouisBrunner/checks-action@v1.6.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        check_id: ${{ steps.check.outputs.check_id }}
        conclusion: ${{ job.status }}
        sha:  ${{github.event.workflow_run.head_sha}}
        repo: ${{github.event.workflow_run.head_repository.full_name}}
        output: |
          {"summary":"finished"}

