name: "TEST integration"

on:
  workflow_dispatch:
  workflow_run:
    workflows: 
      - TEST Unit
    types: 
      - completed

jobs: 
  test-integration-fail:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: test-integration-fail
    defaults:
      run:
        shell: bash
    steps:
    - uses: LouisBrunner/checks-action@v1.6.0
      if: always()
      id: check
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "test-integration-fail-${{ github.run_number }}"
        status: in_progress
        sha:  ${{github.event.workflow_run.head_sha}}
        # output: |
        #   {"title": "integration-failed", "summary":"started ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}
    - name: Checkout cli
      uses: actions/checkout@v3
      with:
        ref: ${{github.event.workflow_run.head_sha}}
    - id: test-secret
      name: test secret
      env:
        test_secret: ${{ secrets.TEST_SECRET }}
        test_var: ${{ vars.TEST_VAR }}
      run: |
        if [ test_secret1 == $test_secret ]; then
          echo "I SEE SECERET"
        fi
        echo  $test_var
        cat testfile
        exit 1
    - uses: LouisBrunner/checks-action@v1.6.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        check_id: ${{ steps.check.outputs.check_id }}
        conclusion: ${{ job.status }}
        sha:  ${{github.event.workflow_run.head_sha}}
        # output: |
        #   {"title": "integration-failed", "summary":"finished ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}

  test-integration:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: test-integration
    defaults:
      run:
        shell: bash
    steps:
    - uses: LouisBrunner/checks-action@v1.6.0
      if: always()
      id: check
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "test-integration-${{ github.run_number }}"
        status: in_progress
        sha:  ${{github.event.workflow_run.head_sha}}
        # output: |
        #   {"title": "integration", "summary":"started ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}
    - name: Checkout cli
      uses: actions/checkout@v3
      with:
        ref: ${{github.event.workflow_run.head_sha}}
    - id: test-secret
      name: test secret
      env:
        test_secret: ${{ secrets.TEST_SECRET }}
        test_var: ${{ vars.TEST_VAR }}
      run: |
        if [ test_secret1 == $test_secret ]; then
          echo "I SEE SECERET"
        fi
        echo  $test_var
        cat testfile
    - uses: LouisBrunner/checks-action@v1.6.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        check_id: ${{ steps.check.outputs.check_id }}
        conclusion: ${{ job.status }}
        sha:  ${{github.event.workflow_run.head_sha}}
        # output: |
        #   {"title": "integration", "summary":"finished ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"}


