name: "TEST Integration"

on:
  workflow_dispatch:
  workflow_run:
    workflows: 
      - TEST Unit
    types: 
      - completed

permissions:
  contents: read

jobs: 
  test-integration:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: test-integration
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout cli
      uses: actions/checkout@v3
      with:
        ref: ${{github.event.workflow_run.head_sha}}
    - id: test-secret
      name: test secret
      env:
        test_secret: ${{ secrets.TEST_SECRET }}
        test_var: ${{ vars.TEST_VAR }}
      run: |
        if [ test_secret1 == $test_secret ]; then
          echo "I SEE SECERET"
        fi
        echo  $test_var
        cat testfile
