on:
  workflow-dispatch:

jobs:
  run-integration-tests:
    name: test job 
    defaults:
      run:
        shell: bash
    
    steps:
    - run: echo PAYLOAD ${{ inputs.os }}
    - run: echo github context ${{ toJson(github) }}
    - run: echo env context ${{ toJson(env) }}
    - run: echo vars context ${{ toJson(vars) }}
    - run: echo job context ${{ toJson(job) }}
    - run: echo steps context ${{ toJson(steps) }}
    - run: echo runner context ${{ toJson(runner) }}
    - run: echo secrets context ${{ toJson(secrets) }}
    - run: echo needs context ${{ toJson(needs) }}
    - run: echo inputs context ${{ toJson(inputs) }}
    - run: echo strategy context ${{ toJson(strategy) }}
    - run: echo matrix context ${{ toJson(matrix) }}
