name: "TEST Unit"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs: 
  test-unit:
    runs-on: ubuntu-latest
    name: test-unit
    defaults:
      run:
        shell: bash
    steps:
    - id: test-exit
      name: test-exit
      env:
        exit_code: 0
      run: |
        exit $exit_code

